version: '3'

includes:
  validate-prerequisites: ./tasks/validate-prerequisites/validate-prerequisite-tasks.yml
  aws-cli: ./tasks/aws-cli/awscli-tasks.yml
  snow-cli:
    taskfile: ./tasks/snow-cli/snowcli-tasks.yml
    dir: ./tasks/snow-cli

env:
  ENV_DIR: .env
  TEMP_DIR: tmp

dotenv: ['{{ .ENV_DIR }}/{{ .DOTENV_FILENAME | default "iceberg.env" }}']

tasks:

  aws-resources-up:
    desc: Validates AWS CLI, creates S3 bucket, generates and creates IAM policy.
    cmds:
      - task: validate-prerequisites:awscli
      - task: aws-cli:make-s3-bucket
        vars:
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          AWS_REGION: $AWS_REGION
      - task: aws-cli:generate-iam-policy-for-s3-bucket-access
        vars:
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          S3_PREFIX: $S3_PREFIX
      - task: aws-cli:create-iam-policy
        vars:
          IAM_POLICY_NAME: $IAM_POLICY_NAME
      - task: aws-cli:generate-trust-policy
      - task: aws-cli:create-iam-role
        vars:
          IAM_ROLE_NAME: $IAM_ROLE_NAME
      - task: aws-cli:attach-policy-to-role

  aws-resources-teardown:
    desc: Deletes the IAM role, IAM policy, and S3 bucket.
    cmds:
      - task: validate-prerequisites:awscli
      - task: aws-cli:detach-policy-from-role
      - task: aws-cli:delete-iam-role
      - task: aws-cli:delete-iam-policy
      - task: aws-cli:delete-s3-bucket
        vars:
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          FORCE: $FORCE

  snowflake-resources-up:
    desc: Validates Snowflake CLI, creates Snowflake external volume.
    cmds:
      - task: validate-prerequisites:snowcli
      - task: snow-cli:create-external-volume
        vars:
          EXTERNAL_VOLUME_NAME: $EXTERNAL_VOLUME_NAME
          S3_PREFIX: $S3_PREFIX
      - task: snow-cli:desc-external-volume
        vars:
          EXTERNAL_VOLUME_NAME: $EXTERNAL_VOLUME_NAME

  snowflake-resources-teardown:
    desc: Drops the Snowflake external volume.
    cmds:
      - task: validate-prerequisites:snowcli
      - task: snow-cli:drop-database-if-exists
        vars:
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME
          DATABASE_NAME: $DATABASE_NAME
      - task: snow-cli:drop-external-volume
        vars:
          EXTERNAL_VOLUME_NAME: $EXTERNAL_VOLUME_NAME

  demo-up:
    desc: Sets up AWS and Snowflake resources for Iceberg demo.
    cmds:
      - task: aws-resources-up
      - task: snowflake-resources-up
      - task: aws-cli:update-trust-policy-with-snowflake-user
      - task: snow-cli:run-init
      - task: snow-cli:upload-files-to-internal-named-stage
        vars:
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME

  demo-teardown:
    desc: Tears down AWS and Snowflake resources for Iceberg demo.
    cmds:
      - task: snowflake-resources-teardown
      - task: aws-resources-teardown
