version: '3'

includes:
  validate-prerequisites: ./tasks/validate-prerequisites/validate-prerequisite-tasks.yml
  aws-cli: ./tasks/aws-cli/awscli-tasks.yml

env:
  ENV_DIR: .env
  TEMP_DIR: tmp

dotenv: ['{{ .ENV_DIR }}/{{ .DOTENV_FILENAME | default "iceberg.env" }}']

tasks:

  aws-resources-up:
    desc: Validates AWS CLI, creates S3 bucket, generates and creates IAM policy.
    cmds:
      - task: validate-prerequisites:awscli
      - task: aws-cli:make-s3-bucket
        vars:
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          AWS_REGION: $AWS_REGION
      - task: aws-cli:generate-iam-policy-for-s3-bucket-access
        vars:
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          S3_PREFIX: $S3_PREFIX
      - task: aws-cli:create-iam-policy
        vars:
          IAM_POLICY_NAME: $IAM_POLICY_NAME

  aws-resources-teardown:
    desc: Deletes the S3 bucket and IAM policy.
    cmds:
      - task: validate-prerequisites:awscli
      - task: aws-cli:delete-s3-bucket
        vars:
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          FORCE: $FORCE
      - task: aws-cli:delete-iam-policy
        vars:
          IAM_POLICY_ARN: $IAM_POLICY_ARN