version: '3'

includes:
  validate-prerequisites: ./tasks/validate-prerequisites/validate-prerequisite-tasks.yml
  aws-cli: ./tasks/aws-cli/awscli-tasks.yml

env:
  ENV_DIR: .env
  TEMP_DIR: tmp

dotenv: ['{{ .ENV_DIR }}/{{ .DOTENV_FILENAME | default "iceberg.env" }}']

tasks:

  make-s3-bucket:
    desc: Create an S3 bucket using AWS CLI.
    cmds:
      - task: aws-cli:make-s3-bucket
        vars:
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          AWS_REGION: $AWS_REGION
