version: '3'

tasks:

  create-uv-venv:
    desc: Create a virtual environment named venv using uv
    status:
      - test -d "{{.ROOT_DIR}}/venv"
    cmds:
      - uv venv "{{.ROOT_DIR}}/venv"

  run-jupyter:
    desc: Run Jupyter notebook in conda environment
    internal: true
    cmds:
      - conda run -n {{.CONDA_ENV_NAME | default "iceberg-lab"}} jupyter notebook {{.SPARK_NOTEBOOK_PATH | default "tasks/python/notebook/horizon_v3_variant_spark.ipynb"}}
