definition_version: 2
env:
  STORAGE_MODE: "set_via_shell_env_var"
  DEMO_WAREHOUSE_NAME: "set_via_shell_env_var"
  DEMO_DATABASE_NAME: "set_via_shell_env_var"
  DEMO_DATABASE_DDL_COMMENT: "set_via_shell_env_var"
  DEMO_SCHEMA_NAME_BRONZE: "set_via_shell_env_var"
  DEMO_SCHEMA_NAME_SILVER: "set_via_shell_env_var"
  DEMO_SCHEMA_NAME_GOLD: "set_via_shell_env_var"
  DEMO_POLICIES_SCHEMA_NAME: "set_via_shell_env_var"
  DEMO_INTERNAL_NAMED_STAGE: "set_via_shell_env_var"
  DEMO_INTERNAL_NAMED_STAGE_COMMENT: "set_via_shell_env_var"
  DEMO_JSON_FILE_FORMAT: "set_via_shell_env_var"
  DEMO_JSON_FILE_FORMAT_COMMENT: "set_via_shell_env_var"
  DEMO_NETWORK_RULE_NAME: "set_via_shell_env_var"
  DEMO_NETWORK_RULE_HOST: "set_via_shell_env_var"
  DEMO_EXTERNAL_ACCESS_INTEGRATION_NAME: "set_via_shell_env_var"
  DEMO_EXTERNAL_ACCESS_INTEGRATION_COMMENT: "set_via_shell_env_var"
  DEMO_NETWORK_POLICY_NAME: "set_via_shell_env_var"
  DEMO_INGRESS_NETWORK_RULE_NAME: "set_via_shell_env_var"
  DEMO_ENGINEER_ROLE_NAME: "set_via_shell_env_var"
  DEMO_ANALYST_ROLE_NAME: "set_via_shell_env_var"
  DEMO_ADMIN_ROLE_NAME: "set_via_shell_env_var"
  DEMO_SEMANTIC_VIEW_NAME: "set_via_shell_env_var"
  DEMO_AGENT_NAME: "set_via_shell_env_var"
  DEMO_SETUP_USER: "UNRESOLVED_SETUP_USER"
  EXTERNAL_VOLUME_NAME: "set_via_shell_env_var"
  STORAGE_BASE_URL: "set_via_shell_env_var"
  STORAGE_AWS_ROLE_ARN: "set_via_shell_env_var"
  TRUST_POLICY_EXTERNAL_ID: "set_via_shell_env_var"
