-- Snowflake Iceberg V3 Comprehensive Guide
-- Script 04: Roles and Grants
-- ============================

USE ROLE ACCOUNTADMIN;
USE DATABASE <% ctx.env.DEMO_DATABASE_NAME %>;
USE WAREHOUSE <% ctx.env.DEMO_WAREHOUSE_NAME %>;

-- ============================================
-- ANALYST ROLE (read-only access)
-- ============================================

-- Warehouse access
GRANT USAGE ON WAREHOUSE <% ctx.env.DEMO_WAREHOUSE_NAME %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;

-- Database and schema access
GRANT USAGE ON DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT USAGE ON SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_BRONZE %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT USAGE ON SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT USAGE ON SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;

-- SELECT on regular tables
GRANT SELECT ON ALL TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_BRONZE %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON ALL TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON ALL TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_BRONZE %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;

-- SELECT on Iceberg tables
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_BRONZE %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_BRONZE %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;

-- SELECT on Dynamic Tables
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %>;

-- ============================================
-- ENGINEER ROLE
-- ============================================

-- Warehouse access
GRANT USAGE ON WAREHOUSE <% ctx.env.DEMO_WAREHOUSE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;

-- Database and schema access
GRANT USAGE ON DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;
GRANT ALL ON SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_BRONZE %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;
GRANT ALL ON SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_SILVER %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;
GRANT ALL ON SCHEMA <% ctx.env.DEMO_DATABASE_NAME %>.<% ctx.env.DEMO_SCHEMA_NAME_GOLD %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;

-- Grant INGEST LINEAGE for external lineage registration
-- This allows the streaming script to register data lineage from IoT sources
-- See: https://docs.snowflake.com/en/user-guide/external-lineage
GRANT INGEST LINEAGE ON ACCOUNT TO ROLE ACCOUNTADMIN;
GRANT INGEST LINEAGE ON ACCOUNT TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;

-- Grant on regular tables
GRANT ALL ON ALL TABLES IN DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;
GRANT ALL ON FUTURE TABLES IN DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;

-- Grant on Iceberg tables
GRANT ALL ON ALL ICEBERG TABLES IN DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;
GRANT ALL ON FUTURE ICEBERG TABLES IN DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;

-- Grant on Dynamic Tables
GRANT ALL ON ALL DYNAMIC TABLES IN DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;
GRANT ALL ON FUTURE DYNAMIC TABLES IN DATABASE <% ctx.env.DEMO_DATABASE_NAME %> TO ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %>;

-- ============================================
-- ADMIN ROLE (inherits both)
-- ============================================
GRANT ROLE <% ctx.env.DEMO_ENGINEER_ROLE_NAME %> TO ROLE <% ctx.env.DEMO_ADMIN_ROLE_NAME %>;
GRANT ROLE <% ctx.env.DEMO_ANALYST_ROLE_NAME %> TO ROLE <% ctx.env.DEMO_ADMIN_ROLE_NAME %>;
