-- Snowflake Iceberg V3 Comprehensive Guide
-- Script 05: Masking Policies, Tags, and Data Metric Functions
-- =============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE <% ctx.env.DEMO_DATABASE_NAME %>;
USE WAREHOUSE <% ctx.env.DEMO_WAREHOUSE_NAME %>;

-- ============================================
-- DATA METRIC FUNCTIONS (DMFs)
-- ============================================

-- DMF: Check for valid geographic coordinates
CREATE OR REPLACE DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_VALID_COORDINATES(
    arg_t TABLE(LATITUDE FLOAT, LONGITUDE FLOAT)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM arg_t
    WHERE LATITUDE < -90 OR LATITUDE > 90
       OR LONGITUDE < -180 OR LONGITUDE > 180
       OR LATITUDE IS NULL OR LONGITUDE IS NULL
$$;

-- DMF: Check for valid vehicle IDs (must match pattern VH-XXXX)
CREATE OR REPLACE DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_VALID_VEHICLE_ID(
    arg_t TABLE(VEHICLE_ID VARCHAR)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM arg_t
    WHERE NOT REGEXP_LIKE(VEHICLE_ID, '^VH-[0-9]{4}$')
       OR VEHICLE_ID IS NULL
$$;

-- DMF: Check for engine temperature anomalies
CREATE OR REPLACE DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_ENGINE_TEMP_ANOMALY(
    arg_t TABLE(ENGINE_TEMP_F FLOAT)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM arg_t
    WHERE ENGINE_TEMP_F < 50 OR ENGINE_TEMP_F > 300
       OR ENGINE_TEMP_F IS NULL
$$;

-- DMF: Check for null variant data
CREATE OR REPLACE DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_NULL_VARIANT(
    arg_t TABLE(VARIANT_COL VARIANT)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM arg_t
    WHERE VARIANT_COL IS NULL
       OR VARIANT_COL = 'null'::VARIANT
       OR OBJECT_KEYS(VARIANT_COL) IS NULL
$$;

-- DMF: Check for duplicate records
CREATE OR REPLACE DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_DUPLICATE_READINGS(
    arg_t TABLE(VEHICLE_ID VARCHAR, READING_TIMESTAMP TIMESTAMP_NTZ)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) - COUNT(DISTINCT CONCAT(VEHICLE_ID, '|', READING_TIMESTAMP::VARCHAR))
    FROM arg_t
$$;

-- ============================================
-- APPLY DMFs TO TABLES
-- ============================================

-- Apply coordinate check to VEHICLE_LOCATIONS
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_LOCATIONS
    ADD DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_VALID_COORDINATES
    ON (LATITUDE, LONGITUDE);

-- Apply vehicle ID check to multiple tables
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.SENSOR_READINGS
    ADD DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_VALID_VEHICLE_ID
    ON (VEHICLE_ID);

ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_LOCATIONS
    ADD DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_VALID_VEHICLE_ID
    ON (VEHICLE_ID);

-- Apply engine temp check to SENSOR_READINGS
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.SENSOR_READINGS
    ADD DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_ENGINE_TEMP_ANOMALY
    ON (ENGINE_TEMP_F);

-- Apply null variant check to tables with VARIANT columns
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_TELEMETRY_STREAM
    ADD DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_NULL_VARIANT
    ON (TELEMETRY_DATA);

ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.MAINTENANCE_LOGS
    ADD DATA METRIC FUNCTION <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.CHECK_NULL_VARIANT
    ON (LOG_DATA);
