-- Snowflake Iceberg V3 Comprehensive Guide
-- Script 05: Masking Policies, Tags, and Data Metric Functions
-- =============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE <% ctx.env.DEMO_DATABASE_NAME %>;
USE WAREHOUSE <% ctx.env.DEMO_WAREHOUSE_NAME %>;

-- ============================================
-- TAGS FOR CLASSIFICATION
-- ============================================

-- Create custom tags
CREATE TAG IF NOT EXISTS <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_SENSITIVITY
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data sensitivity classification';

CREATE TAG IF NOT EXISTS <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.PII_TYPE
    ALLOWED_VALUES 'NAME', 'EMAIL', 'PHONE', 'ADDRESS', 'SSN', 'FINANCIAL'
    COMMENT = 'Type of personally identifiable information';

CREATE TAG IF NOT EXISTS <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_DOMAIN
    ALLOWED_VALUES 'TELEMETRY', 'MAINTENANCE', 'LOCATION', 'DRIVER', 'VEHICLE'
    COMMENT = 'Business domain for the data';

-- Apply tags to tables
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_REGISTRY SET TAG
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_SENSITIVITY = 'CONFIDENTIAL',
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_DOMAIN = 'DRIVER';

ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_TELEMETRY_STREAM SET TAG
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_SENSITIVITY = 'INTERNAL',
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_DOMAIN = 'TELEMETRY';

ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_LOCATIONS SET TAG
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_SENSITIVITY = 'INTERNAL',
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_DOMAIN = 'LOCATION';

ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.MAINTENANCE_LOGS SET TAG
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_SENSITIVITY = 'INTERNAL',
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_DOMAIN = 'MAINTENANCE';

ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.SENSOR_READINGS SET TAG
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_SENSITIVITY = 'INTERNAL',
    <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.DATA_DOMAIN = 'TELEMETRY';

-- Apply PII tags to columns
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_REGISTRY MODIFY COLUMN DRIVER_NAME SET TAG <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.PII_TYPE = 'NAME';
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_REGISTRY MODIFY COLUMN DRIVER_EMAIL SET TAG <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.PII_TYPE = 'EMAIL';
ALTER ICEBERG TABLE <% ctx.env.DEMO_SCHEMA_NAME_BRONZE %>.VEHICLE_REGISTRY MODIFY COLUMN DRIVER_PHONE SET TAG <% ctx.env.DEMO_POLICIES_SCHEMA_NAME %>.PII_TYPE = 'PHONE';
